#API Conversão-Temperatura
apiVersion: apps/v1
kind: Deployment
metadata:
  name: convpeso
spec:
  replicas: 1
  selector:
    matchLabels:
      app: convpeso
  template:
    metadata:
      labels:
        app: convpeso
    spec:
      containers:
        - name: convtemp
          image: raulc27/conversao-peso:latest
          ports:
            - containerPort: 5000
---
# Service da aplicação
apiVersion: v1
kind: Service
metadata:
  name: convpeso
spec:
  selector:
    app: convpeso
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30000
  type: NodePort
